# Generated by Django 5.0.6 on 2025-06-24 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=255)),
                ('objet', models.TextField()),
                ('maitre_ouvrage', models.CharField(max_length=255)),
                ('lieu_execution', models.CharField(blank=True, max_length=255, null=True)),
                ('date_limite', models.DateField()),
                ('source_site', models.CharField(max_length=255)),
                ('sended', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SourceSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('actif', models.BooleanField(default=True)),
            ],
        ),
    ]
